# Generated by Django 3.2 on 2022-06-24 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0010_auto_20220624_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlinecase',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkout.order'),
        ),
        migrations.AlterField(
            model_name='orderlinecpu',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkout.order'),
        ),
        migrations.AlterField(
            model_name='orderlinegpu',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkout.order'),
        ),
        migrations.AlterField(
            model_name='orderlinemotherboard',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkout.order'),
        ),
        migrations.AlterField(
            model_name='orderlinepsu',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkout.order'),
        ),
        migrations.AlterField(
            model_name='orderlineram',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkout.order'),
        ),
        migrations.AlterField(
            model_name='orderlinestorage',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkout.order'),
        ),
    ]
