# Generated by Django 3.2 on 2022-06-24 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0011_auto_20220624_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlinecase',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineitem_case', to='checkout.order'),
        ),
        migrations.AlterField(
            model_name='orderlinecpu',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineitem_cpu', to='checkout.order'),
        ),
        migrations.AlterField(
            model_name='orderlinegpu',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineitem_gpu', to='checkout.order'),
        ),
        migrations.AlterField(
            model_name='orderlinemotherboard',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineitem_motherboard', to='checkout.order'),
        ),
        migrations.AlterField(
            model_name='orderlinepsu',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineitem_psu', to='checkout.order'),
        ),
        migrations.AlterField(
            model_name='orderlineram',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineitem_ram', to='checkout.order'),
        ),
        migrations.AlterField(
            model_name='orderlinestorage',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineitem_storage', to='checkout.order'),
        ),
    ]
