# Generated by Django 3.2 on 2022-06-26 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casereview',
            name='score',
            field=models.IntegerField(choices=[(5, 'Very Satisfied'), (4, 'Satisfied'), (3, 'Neutral'), (2, 'Dissatisfied'), (1, 'Very Dissatisfied')], default=3),
        ),
        migrations.AlterField(
            model_name='cpureview',
            name='score',
            field=models.IntegerField(choices=[(5, 'Very Satisfied'), (4, 'Satisfied'), (3, 'Neutral'), (2, 'Dissatisfied'), (1, 'Very Dissatisfied')], default=3),
        ),
        migrations.AlterField(
            model_name='gpureview',
            name='score',
            field=models.IntegerField(choices=[(5, 'Very Satisfied'), (4, 'Satisfied'), (3, 'Neutral'), (2, 'Dissatisfied'), (1, 'Very Dissatisfied')], default=3),
        ),
        migrations.AlterField(
            model_name='motherboardreview',
            name='score',
            field=models.IntegerField(choices=[(5, 'Very Satisfied'), (4, 'Satisfied'), (3, 'Neutral'), (2, 'Dissatisfied'), (1, 'Very Dissatisfied')], default=3),
        ),
        migrations.AlterField(
            model_name='psureview',
            name='score',
            field=models.IntegerField(choices=[(5, 'Very Satisfied'), (4, 'Satisfied'), (3, 'Neutral'), (2, 'Dissatisfied'), (1, 'Very Dissatisfied')], default=3),
        ),
        migrations.AlterField(
            model_name='ramreview',
            name='score',
            field=models.IntegerField(choices=[(5, 'Very Satisfied'), (4, 'Satisfied'), (3, 'Neutral'), (2, 'Dissatisfied'), (1, 'Very Dissatisfied')], default=3),
        ),
        migrations.AlterField(
            model_name='storagereview',
            name='score',
            field=models.IntegerField(choices=[(5, 'Very Satisfied'), (4, 'Satisfied'), (3, 'Neutral'), (2, 'Dissatisfied'), (1, 'Very Dissatisfied')], default=3),
        ),
    ]
