# Generated by Django 3.2 on 2022-06-24 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0006_alter_psu_e_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='DealStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_was', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('price_new', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('deal_ends', models.DateTimeField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_deal', to='products.storage')),
            ],
        ),
        migrations.CreateModel(
            name='DealRam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_was', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('price_new', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('deal_ends', models.DateTimeField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ram_deal', to='products.ram')),
            ],
        ),
        migrations.CreateModel(
            name='DealPsu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_was', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('price_new', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('deal_ends', models.DateTimeField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='psu_deal', to='products.psu')),
            ],
        ),
        migrations.CreateModel(
            name='DealMotherboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_was', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('price_new', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('deal_ends', models.DateTimeField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='motherboard_deal', to='products.motherboard')),
            ],
        ),
        migrations.CreateModel(
            name='DealGpu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_was', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('price_new', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('deal_ends', models.DateTimeField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gpu_deal', to='products.gpu')),
            ],
        ),
        migrations.CreateModel(
            name='DealCpu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_was', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('price_new', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('deal_ends', models.DateTimeField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cpu_deal', to='products.cpu')),
            ],
        ),
        migrations.CreateModel(
            name='DealCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_was', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('price_new', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('deal_ends', models.DateTimeField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_deal', to='products.case')),
            ],
        ),
    ]
