# Generated by Django 3.2 on 2022-06-24 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealcase',
            name='deal_ends',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='dealcpu',
            name='deal_ends',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='dealgpu',
            name='deal_ends',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='dealmotherboard',
            name='deal_ends',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='dealpsu',
            name='deal_ends',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='dealram',
            name='deal_ends',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='dealstorage',
            name='deal_ends',
            field=models.DateField(),
        ),
    ]
