# Generated by Django 3.2 on 2022-05-20 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=254)),
                ('manufacturer', models.CharField(max_length=254)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('rating', models.DecimalField(blank=True, choices=[(1, 'Very Dissatisfied'), (2, 'Dissatisfied'), (3, 'Neutral'), (4, 'Satisfied'), (5, 'Very Satisfied')], decimal_places=2, max_digits=6, null=True)),
                ('mobo_sizes', models.CharField(choices=[('mini_atx', 'Mini ATX'), ('micro_atx', 'Micro ATX'), ('atx', 'ATX'), ('e_atx', 'EATX')], max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Cpu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=254)),
                ('manufacturer', models.CharField(max_length=254)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('rating', models.DecimalField(blank=True, choices=[(1, 'Very Dissatisfied'), (2, 'Dissatisfied'), (3, 'Neutral'), (4, 'Satisfied'), (5, 'Very Satisfied')], decimal_places=2, max_digits=6, null=True)),
                ('socket', models.CharField(choices=[('AM4', 'AM4'), ('1700', '1700'), ('1200', '1200'), ('2066', '2066')], max_length=254)),
                ('core_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Gpu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=254)),
                ('manufacturer', models.CharField(max_length=254)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('rating', models.DecimalField(blank=True, choices=[(1, 'Very Dissatisfied'), (2, 'Dissatisfied'), (3, 'Neutral'), (4, 'Satisfied'), (5, 'Very Satisfied')], decimal_places=2, max_digits=6, null=True)),
                ('speed', models.IntegerField()),
                ('memory_capacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Motherboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=254)),
                ('manufacturer', models.CharField(max_length=254)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('rating', models.DecimalField(blank=True, choices=[(1, 'Very Dissatisfied'), (2, 'Dissatisfied'), (3, 'Neutral'), (4, 'Satisfied'), (5, 'Very Satisfied')], decimal_places=2, max_digits=6, null=True)),
                ('size', models.CharField(choices=[('mini_atx', 'Mini ATX'), ('micro_atx', 'Micro ATX'), ('atx', 'ATX'), ('e_atx', 'EATX')], max_length=254)),
                ('socket', models.CharField(choices=[('AM4', 'AM4'), ('1700', '1700'), ('1200', '1200'), ('2066', '2066')], max_length=254)),
                ('ram_type', models.CharField(choices=[('ddr3', 'DDR3'), ('ddr4', 'DDR4'), ('ddr5', 'DDR5')], max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Psu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=254)),
                ('manufacturer', models.CharField(max_length=254)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('rating', models.DecimalField(blank=True, choices=[(1, 'Very Dissatisfied'), (2, 'Dissatisfied'), (3, 'Neutral'), (4, 'Satisfied'), (5, 'Very Satisfied')], decimal_places=2, max_digits=6, null=True)),
                ('wattage', models.IntegerField()),
                ('category', models.CharField(choices=[('80plus', '80 PLUS'), ('80plus_bronze', '80 PLUS Bronze'), ('80plus_silver', '80 PLUS Silver'), ('80plus_gold', '80 PLUS Gold'), ('80plus_platinum', '80 PLUS Platinum'), ('80plus_titanium', '80 PLUS Titanium')], max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Ram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=254)),
                ('manufacturer', models.CharField(max_length=254)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('rating', models.DecimalField(blank=True, choices=[(1, 'Very Dissatisfied'), (2, 'Dissatisfied'), (3, 'Neutral'), (4, 'Satisfied'), (5, 'Very Satisfied')], decimal_places=2, max_digits=6, null=True)),
                ('speed', models.IntegerField()),
                ('capacity', models.IntegerField()),
                ('type', models.CharField(choices=[('ddr3', 'DDR3'), ('ddr4', 'DDR4'), ('ddr5', 'DDR5')], max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=254)),
                ('manufacturer', models.CharField(max_length=254)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('rating', models.DecimalField(blank=True, choices=[(1, 'Very Dissatisfied'), (2, 'Dissatisfied'), (3, 'Neutral'), (4, 'Satisfied'), (5, 'Very Satisfied')], decimal_places=2, max_digits=6, null=True)),
                ('capacity', models.IntegerField()),
                ('speed', models.IntegerField()),
            ],
        ),
    ]
