# Generated by Django 3.2 on 2022-05-31 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20220527_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='psu',
            name='e_category',
            field=models.CharField(choices=[('80plus', '80 PLUS'), ('80plus_bronze', '80 PLUS Bronze'), ('80plus_silver', '80 PLUS Silver'), ('80plus_gold', '80 PLUS Gold'), ('80plus_platinum', '80 PLUS Platinum'), ('80plus_titanium', '80 PLUS Titanium')], default='80plus', max_length=254),
        ),
    ]
